### ISSUE TITLE
请问下怎么配置邮箱地址啊？

### ISSUE THREAD

**Issue by ashu0000008** [baibinghere/huobi-autotrading#1]
如何测试下？

**Comment by baibinghere** [comment]
我用的是QQ邮箱，在配置里面，打开IMAP，生成授权码，把相应的数据填入settings.py就可以了。
测试而言，你只需要直接执行python3 -m app.service.mailagent即可。

root@baibinghere:~/work/huobi-autotrading# python3 -m app.service.mailagent
发送成功
最新邮件: 测试
接收成功
